In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from datetime import datetime

In [56]:
df = pd.read_csv('data/Full_combined_tickers.csv')
df = df.reset_index(drop=True)
df = df.drop(df.columns[[0, 1]], axis=1) 
df.head()

              datetime    open    high     low   close   volume   symbol
0  2022-01-01 00:00:00  0.4166  0.4204  0.4162  0.4192  26337.3  POWRUSD
1  2022-01-01 01:00:00  0.4199  0.4250  0.4192  0.4211  56980.8  POWRUSD
2  2022-01-01 02:00:00  0.4211  0.4229  0.4186  0.4186  27973.3  POWRUSD
3  2022-01-01 03:00:00  0.4189  0.4204  0.4185  0.4186  26386.4  POWRUSD
4  2022-01-01 04:00:00  0.4194  0.4197  0.4173  0.4183  16900.1  POWRUSD

In [57]:
print(df.dtypes)

datetime     object
open        float64
high        float64
low         float64
close       float64
volume      float64
symbol       object
dtype: object

In [59]:
print(df['symbol'].value_counts()) #391 products in total

POWRUSD      3624
TWTBUSD      3624
ALICEBUSD    3624
DEGOBUSD     3624
PONDBUSD     3624
             ...
BTCTUSD      3624
IOTXUSD      3624
LPTUSD       3624
MANAUSD      3624
JOEBUSD      3624
Name: symbol, Length: 391, dtype: int64

In [61]:
cur_usd = np.unique(df["symbol"])
print(len(cur_usd))

391

In [62]:
df_usd = df.loc[df["symbol"] == cur_usd[0]]
df_usd = df_usd.sort_values(by='datetime')
df_usd["datetime"] = pd.to_datetime(df_usd["datetime"])
df_usd.set_index("datetime", inplace=True)
df_usd = df_usd.drop(['symbol'], axis=1)
df_usd.columns = [cur_usd[0]+'_open', cur_usd[0]+'_high', cur_usd[0]+'_low', cur_usd[0]+'_close', cur_usd[0]+'_volume']

for i in range(1, len(cur_usd)):
    df_temp = df.loc[df["symbol"] == cur_usd[i]]
    df_temp = df_temp.sort_values(by='datetime')
    df_temp["datetime"] = pd.to_datetime(df_temp["datetime"])
    df_temp.set_index("datetime", inplace=True)
    df_temp = df_temp.drop(['symbol'], axis=1)
    df_temp.columns = [cur_usd[i]+'_open', cur_usd[i]+'_high', cur_usd[i]+'_low', cur_usd[i]+'_close', cur_usd[i]+'_volume']
    
    df_usd = df_usd.join(df_temp)

df_usd

,1INCHBUSD_open,1INCHBUSD_high,1INCHBUSD_low,1INCHBUSD_close,1INCHBUSD_volume,1INCHUSD_open,1INCHUSD_high,1INCHUSD_low,1INCHUSD_close,1INCHUSD_volume,...,ZRXBUSD_open,ZRXBUSD_high,ZRXBUSD_low,ZRXBUSD_close,ZRXBUSD_volume,ZRXUSD_open,ZRXUSD_high,ZRXUSD_low,ZRXUSD_close,ZRXUSD_volume
datetime,,,,,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00,2.410,2.450,2.406,2.429,27034.1,2.390,2.420,2.390,2.420,47726.30,...,0.8225,0.8375,0.8225,0.8349,2957.0,0.803274,0.815819,0.803274,0.815819,124094.48027
2022-01-01 01:00:00,2.434,2.441,2.421,2.424,15641.5,2.420,2.440,2.410,2.440,109643.15,...,0.8367,0.8367,0.8262,0.8262,7690.0,0.815761,0.818488,0.812232,0.816939,430003.38704
2022-01-01 02:00:00,2.423,2.444,2.418,2.434,10500.5,2.430,2.450,2.430,2.440,22534.85,...,0.8249,0.8305,0.8249,0.8296,1352.0,0.817332,0.841967,0.816370,0.825341,545121.67633
2022-01-01 03:00:00,2.433,2.449,2.433,2.435,11621.9,2.430,2.450,2.430,2.430,16066.99,...,0.8310,0.8327,0.8271,0.8271,5814.0,0.825479,0.826189,0.819242,0.821205,174704.12975
2022-01-01 04:00:00,2.436,2.454,2.415,2.428,18122.9,2.420,2.430,2.400,2.400,35143.16,...,0.8262,0.8326,0.8239,0.8326,4731.0,0.822383,0.824401,0.814999,0.821184,109516.28991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-31 19:00:00,0.967,0.972,0.953,0.964,62571.4,0.966,0.972,0.966,0.969,34241.32,...,0.4214,0.4370,0.4193,0.4309,118348.0,0.415042,0.417221,0.412115,0.414259,146124.40386
2022-05-31 20:00:00,0.963,0.965,0.960,0.965,19140.8,0.969,0.970,0.966,0.968,5846.26,...,0.4270,0.4432,0.4252,0.4308,148208.0,0.414923,0.421796,0.414923,0.421796,48940.19297
2022-05-31 21:00:00,0.964,0.964,0.958,0.961,15210.7,0.969,0.970,0.967,0.969,5068.87,...,0.4295,0.4445,0.4295,0.4410,149321.0,0.421837,0.421837,0.416822,0.417250,35316.14544
2022-05-31 22:00:00,0.960,0.966,0.953,0.965,35818.9,0.967,0.971,0.967,0.971,786.32,...,0.4385,0.4395,0.4250,0.4289,105858.0,0.417112,0.421681,0.416555,0.420949,34868.68387
2022-05-31 23:00:00,0.965,0.981,0.961,0.978,27142.4,0.972,0.972,0.966,0.967,10317.00,...,0.4289,0.4363,0.4231,0.4324,135402.0,0.420771,0.423000,0.417373,0.420407,78304.47144

In [65]:
df_usd.to_csv("data/flattened_data.csv")